name: check-installation
on:
  workflow_dispatch:
  push:
    branches:
      - 1x*

jobs:
  build:
    strategy:
      matrix:
        include:
          - container: ubuntu/python:3.8-20.04_edge
            distro: ubuntu-20.04
          - container: ubuntu/python:3.10-22.04_edge
            distro: ubuntu-22.04

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y make git coreutils

      - uses: actions/checkout@v4

      - name: Build & Install
        run: |
          make && make install

      - name: Get bqckup version
        run: |
          version=$(python -c "exec(open('constant/__init__.py').read()); print(f'v{VERSION}')")
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create tarball
        run: |
          cd ./dist
          tar -czf ../bqckup-${{ env.VERSION }}-${{ matrix.distro }}.tar.gz bqckup

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          generate_release_notes: true
          files: |
            ./bqckup-${{ env.VERSION }}-${{ matrix.distro }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
