name: check-installation
on:
  workflow_dispatch:
  push:
    branches:
      - 1x*

jobs:
  build:
    strategy:
      matrix:
        include:
          - os-version: 22.04
            python: "3.8"
          - os-version: 22.04
            python: "3.10"

    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.os-version }}

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python${{ matrix.python }} python${{ matrix.python }}-dev python3-pip make git

      - uses: actions/checkout@v4

      - name: Setup Python symlink
        run: |
          update-alternatives --install /usr/bin/python python /usr/bin/python${{ matrix.python }} 1
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${{ matrix.python }} 1

      - name: Build & Install
        run: |
          make && make install

      - name: Get bqckup version
        run: |
          version=$(python -c "exec(open('constant/__init__.py').read()); print(f'v{VERSION}')")
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create tarball
        run: |
          cd ./dist
          tar -czf ../bqckup-${{ env.VERSION }}-ubuntu-${{ matrix.os-version }}.tar.gz bqckup

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          generate_release_notes: true
          files: |
            ./bqckup-${{ env.VERSION }}-ubuntu-${{ matrix.os-version }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}